version: "3.3"
services:
  frontend:
    image: node:17-alpine3.12
    container_name: frontend
    working_dir: /frontend
    volumes:
      - ./app/frontend:/frontend
    ports:
      - "80:80"
    entrypoint: >
      sh -c "npm ci
      && npm run dev"
  backend:
    image: node:17-alpine3.12
    container_name: backend
    working_dir: /backend
    volumes:
      - ./app/backend:/backend
    ports:
      - "3000:3000"
    entrypoint: >
      sh -c "npm ci
      && npm run start:dev"