name: CD
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "**/.gitignore"
      - "images/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/goinfre/tchatong
            sudo docker-compose down
            git restore .
            git pull
            sed -i 'docker-compose.yaml' -e 's/npm run dev/npm run build \&\& npm start/'
            sed -i 'docker-compose.yaml' -e 's/# //g'
            sed -i './app/proxy/srcs/nginx.conf' -e 's/# //'
            sed -i './app/backend/main.go' -e 's/gin.DebugMode/gin.ReleaseMode/g'
            sudo chmod -R 777 ./app/db/data
            sudo docker-compose up -d --build
